import type { NamePool } from "./countries"

interface Pool {
  male: string[]
  female: string[]
  last: string[]
  /** Family name is written first (e.g. Chinese, Korean, Hungarian). */
  familyFirst?: boolean
  /** Patronymic-style or single names: no family name shown. */
  noFamily?: boolean
}

const s = (x: string) => x.split(" ").map((n) => n.replace(/_/g, " "))

export const NAME_POOLS: Record<NamePool, Pool> = {
  anglo: { male: s("James John Michael David Daniel Liam Noah Ethan Ryan Jack Oliver William Tyler Marcus"), female: s("Mary Emma Olivia Sarah Jessica Emily Ava Sophie Chloe Grace Hannah Megan Ashley Ruby"), last: s("Smith Johnson Williams Brown Jones Miller Davis Wilson Taylor Clarke Walker Hughes Murphy Kelly Robinson Thompson") },
  hispanic: { male: s("José Juan Luis Carlos Miguel Javier Diego Alejandro Santiago Mateo Andrés Fernando Pablo Jorge"), female: s("María Ana Lucía Sofía Valentina Camila Isabel Gabriela Daniela Carmen Paula Elena Mariana Ximena"), last: s("García Rodríguez Martínez Hernández López González Pérez Sánchez Ramírez Torres Flores Rivera Gómez Díaz Morales Castro") },
  lusophone: { male: s("João Pedro Lucas Gabriel Rafael Mateus Thiago Bruno Carlos Antônio Francisco Paulo Miguel Tiago"), female: s("Ana Maria Juliana Beatriz Larissa Fernanda Mariana Camila Francisca Joana Inês Rita Luana Adriana"), last: s("Silva Santos Oliveira Souza Pereira Costa Ferreira Rodrigues Almeida Lima Carvalho Gomes Martins Ribeiro") },
  french: { male: s("Jean Pierre Louis Lucas Hugo Théo Nicolas Antoine Julien Mathieu Gabriel Jules Thomas Wilson"), female: s("Marie Camille Léa Chloé Manon Inès Juliette Sophie Claire Élise Louise Céline Nadège Mireille"), last: s("Martin Bernard Dubois Thomas Robert Richard Petit Durand Leroy Moreau Laurent Lefebvre Joseph Pierre-Louis") },
  german: { male: s("Lukas Leon Jonas Felix Maximilian Paul Tobias Stefan Andreas Michael Thomas Florian Niklas Jan"), female: s("Anna Lena Laura Lea Sophie Julia Katharina Sabine Petra Hannah Marie Johanna Clara Nina"), last: s("Müller Schmidt Schneider Fischer Weber Meyer Wagner Becker Schulz Hoffmann Koch Bauer Richter Wolf Huber") },
  dutch: { male: s("Daan Sem Lucas Bram Thijs Ruben Jeroen Pieter Joost Sander Lars Wouter Bas Milan"), female: s("Emma Julia Sophie Lotte Anouk Fleur Sanne Eva Lieke Iris Noor Femke Marieke Saskia"), last: s("de_Jong Jansen de_Vries van_den_Berg Bakker Visser Smit Meijer Mulder de_Boer Peeters Janssens Claes Maes") },
  nordic: { male: s("Lars Erik Anders Johan Mikael Henrik Oskar Magnus Olav Jonas Mathias Eino Mikko Gunnar"), female: s("Anna Emma Ingrid Sofie Maja Astrid Elin Karin Freja Ida Nora Aino Linnea Sigrid"), last: s("Andersson Johansson Hansen Nielsen Larsen Olsen Karlsson Nilsson Virtanen Korhonen Berg Lindqvist Jensen Pedersen") },
  italian: { male: s("Marco Luca Giuseppe Francesco Alessandro Andrea Matteo Lorenzo Giovanni Antonio Davide Simone Paolo Stefano"), female: s("Giulia Francesca Chiara Sara Martina Alessia Valentina Giorgia Elena Anna Federica Silvia Laura Paola"), last: s("Rossi Russo Ferrari Esposito Bianchi Romano Colombo Ricci Marino Greco Bruno Gallo Conti De Luca") },
  slavicEast: { male: s("Alexander Dmitry Sergei Ivan Andrei Mikhail Nikolai Oleksandr Taras Vladimir Pavel Artem Maksim Yuri"), female: s("Anna Maria Elena Olga Natalia Tatiana Irina Svetlana Daria Anastasia Yulia Oksana Kateryna Ekaterina"), last: s("Ivanov Smirnov Kuznetsov Popov Sokolov Petrov Volkov Shevchenko Kovalenko Bondarenko Melnyk Novikov Morozov Lebedev") },
  slavicWest: { male: s("Jakub Jan Piotr Tomasz Krzysztof Michał Paweł Marek Lukáš Petr Martin Ondřej Kamil Adam"), female: s("Anna Katarzyna Magdalena Agnieszka Joanna Zuzana Tereza Eva Monika Karolina Natalia Lucie Barbara Marta"), last: s("Nowak Kowalski Wiśniewski Wójcik Kowalczyk Novák Svoboda Dvořák Černý Kamiński Lewandowski Zieliński Horváth Kováč") },
  balkan: { male: s("Marko Nikola Stefan Luka Aleksandar Ivan Milan Dragan Georgi Dimitar Ardit Emir Bence Dávid"), female: s("Ana Milica Jelena Marija Ivana Elena Maria Petra Teodora Amra Ajla Lejla Eszter Réka"), last: s("Jovanović Petrović Nikolić Horvat Kovačević Ivanov Georgiev Dimitrov Hoxha Begović Hodžić Nagy Kovács Novak") },
  romanian: { male: s("Andrei Alexandru Mihai Ion Gabriel Ștefan Florin Cristian Adrian Vasile Radu Bogdan Ionuț Victor"), female: s("Maria Elena Ioana Andreea Alexandra Ana Mihaela Cristina Gabriela Daniela Irina Raluca Diana Oana"), last: s("Popescu Ionescu Popa Pop Radu Dumitru Stan Stoica Gheorghe Matei Ciobanu Rusu Munteanu Constantin") },
  baltic: { male: s("Jonas Mantas Lukas Tomas Andris Jānis Mārtiņš Kristaps Rasmus Karl Martin Markus Artūras Edgars"), female: s("Rūta Ieva Austėja Laura Anna Līga Ilze Kristīne Maria Liis Kadri Triin Gabija Elīna"), last: s("Kazlauskas Jankauskas Petrauskas Bērziņš Kalniņš Ozoliņš Tamm Saar Sepp Mägi Vasiliauskas Liepiņš Kask Pētersons") },
  greek: { male: s("Georgios Ioannis Konstantinos Dimitrios Nikolaos Panagiotis Christos Vasileios Andreas Michail Alexandros Stavros Petros Spyros"), female: s("Maria Eleni Aikaterini Vasiliki Sofia Angeliki Georgia Dimitra Konstantina Ioanna Despina Christina Anna Paraskevi"), last: s("Papadopoulos Papadakis Georgiou Nikolaou Dimitriou Konstantinou Ioannou Christodoulou Vlachos Pappas Oikonomou Makris Antoniou Karagiannis") },
  caucasus: { male: s("Giorgi Davit Luka Nikoloz Levan Irakli Aram Armen Tigran Hayk Gor Narek Zurab Sandro"), female: s("Nino Mariam Ana Tamar Elene Salome Ani Anahit Lilit Mane Nare Gayane Ketevan Natia"), last: s("Beridze Kapanadze Gelashvili Maisuradze Giorgadze Lomidze Hovhannisyan Harutyunyan Sargsyan Grigoryan Petrosyan Khachatryan Mamedov Tsiklauri") },
  arabic: { male: s("Mohammed Ahmed Ali Omar Youssef Hassan Ibrahim Khaled Mahmoud Mustafa Abdullah Karim Tariq Hamza"), female: s("Fatima Aisha Mariam Nour Layla Sara Zainab Huda Amira Salma Yasmin Rania Hala Khadija"), last: s("Al-Sayed Haddad Hassan Mansour Khalil Nasser Saleh Ibrahim Abdallah Hamdan Darwish Farouk Benali El-Amin Bouzid Othman") },
  persian: { male: s("Mohammad Ali Reza Hossein Mehdi Amir Hamid Javad Ahmad Mostafa Farhad Dariush Sohrab Rustam"), female: s("Fatemeh Zahra Maryam Narges Leila Shirin Parisa Mahsa Sara Niloufar Farzaneh Roya Zarina Malalai"), last: s("Hosseini Mohammadi Rezaei Ahmadi Karimi Jafari Rahimi Moradi Sadeghi Ghorbani Rahmonov Safarov Popal Wardak") },
  turkic: { male: s("Mehmet Mustafa Ahmet Ali Hüseyin Emre Murat Yusuf Burak Rustam Timur Nurlan Daniyar Elnur"), female: s("Ayşe Fatma Zeynep Elif Emine Merve Aigerim Dilnoza Madina Gulnara Aylin Leyla Nilufar Saule"), last: s("Yılmaz Kaya Demir Şahin Çelik Yıldız Öztürk Aydın Karimov Nazarbayev Aliyev Mammadov Tursunov Sadykov") },
  hindi: { male: s("Rahul Amit Rajesh Suresh Vikram Arjun Rohan Sanjay Anil Ravi Deepak Manoj Prakash Aarav Bikash"), female: s("Priya Anjali Pooja Sunita Neha Kavita Lakshmi Deepika Asha Meera Rekha Sita Divya Ananya Sarita"), last: s("Sharma Kumar Singh Patel Gupta Yadav Reddy Nair Iyer Das Verma Joshi Mishra Shrestha Thapa Rao") },
  urdu: { male: s("Muhammad Ali Ahmed Hassan Bilal Usman Imran Faisal Zubair Asif Kamran Tariq Shahid Waqas"), female: s("Ayesha Fatima Sana Zainab Hira Mehwish Saima Nadia Rabia Bushra Amna Khadija Iqra Maryam"), last: s("Khan Ahmed Malik Hussain Shah Butt Qureshi Chaudhry Sheikh Raza Iqbal Mirza Akhtar Baloch") },
  bengali: { male: s("Mohammad Abdul Rahim Karim Rafiq Shakil Tanvir Arif Sohel Jahid Habib Masud Rakib Sumon"), female: s("Fatema Nasrin Taslima Shirin Rokeya Sumaiya Nusrat Farzana Shathi Mitu Rupa Jannatul Sharmin Moushumi"), last: s("Rahman Hossain Islam Ahmed Uddin Akter Begum Chowdhury Sarkar Mia Khatun Haque Das Roy") },
  sinhala: { male: s("Nuwan Kasun Chaminda Ruwan Pradeep Saman Dinesh Lahiru Thilina Kumar Suresh Ravi Mohamed Kamal"), female: s("Nadeesha Dilani Chathurika Sanduni Ishara Kumari Nilmini Shalini Malini Fathima Priyanka Tharushi Anusha Hasini"), last: s("Perera Fernando de_Silva Bandara Jayasinghe Wickramasinghe Rajapaksa Dissanayake Herath Gunawardena Kumara Sivakumar Ratnayake Mendis") },
  chinese: { familyFirst: true, male: s("Wei Hao Jun Lei Yang Jie Tao Ming Qiang Bo Chen Yu Zhiwei Jianguo"), female: s("Fang Jing Li Na Min Yan Xiu Lan Hui Ying Mei Xin Ting Yuxuan"), last: s("Wang Li Zhang Liu Chen Yang Huang Zhao Wu Zhou Xu Sun Ma Zhu Hu Lin") },
  japanese: { familyFirst: true, male: s("Haruto Sota Yuto Hiroshi Takeshi Kenji Daiki Ryo Shota Kazuki Takumi Yuki Kenta Makoto"), female: s("Yui Hana Sakura Yuna Aoi Misaki Akiko Yoko Keiko Haruka Mai Natsuki Emi Rin"), last: s("Sato Suzuki Takahashi Tanaka Watanabe Ito Yamamoto Nakamura Kobayashi Kato Yoshida Yamada Sasaki Matsumoto") },
  korean: { familyFirst: true, male: s("Min-jun Seo-jun Ji-ho Do-yun Jun-seo Hyun-woo Sung-min Jae-won Dong-hyun Young-ho Tae-yang Woo-jin Chul-soo Kwang-ho"), female: s("Seo-yeon Ji-woo Ha-eun Min-seo Soo-ah Ji-yeon Eun-ji Hye-jin Yu-na Su-bin Ye-jin Mi-kyung Young-hee Jung-hwa"), last: s("Kim Lee Park Choi Jung Kang Cho Yoon Jang Lim Han Shin Oh Seo") },
  vietnamese: { familyFirst: true, male: s("Minh Hùng Tuấn Dũng Nam Huy Long Phúc Quang Thành Khoa Đức Hải Bảo"), female: s("Linh Hương Lan Mai Ngọc Thảo Trang Hoa Anh Phương Huyền Hạnh Thu Vy"), last: s("Nguyễn Trần Lê Phạm Hoàng Huỳnh Phan Vũ Võ Đặng Bùi Đỗ Hồ Ngô") },
  thai: { male: s("Somchai Somsak Anan Chaiya Prasert Wichai Kittisak Narong Thanawat Pongsakorn Souksavanh Khamphan Boonmee Nattapong"), female: s("Somsri Malee Siriporn Kanya Ploy Nittaya Wanida Ratana Pimchanok Supaporn Manivanh Chanthala Duangjai Achara"), last: s("Saetang Srisuk Wongsawat Chaiyaporn Rattanakorn Thongchai Boonyarat Phommachanh Keomany Sriwong Kaewmanee Jaidee Chanthavong Inthavong") },
  khmer: { familyFirst: true, male: s("Sokha Dara Vuthy Sopheak Rithy Chenda Piseth Visal Bunthan Sambath Vannak Kosal Rotha Samnang"), female: s("Sreymom Sophea Chanthy Bopha Sreyleak Dalin Kunthea Malis Raksmey Sokunthea Vanna Theary Leakhena Navy"), last: s("Sok Chea Kim Heng Chan Ly Meas Nhem Keo Seng Phan Ouk Pich Touch") },
  burmese: { noFamily: true, male: s("Aung Kyaw Min Zaw Htet Thura Ko Naing Soe Win Myo Thant Tun Hlaing"), female: s("Aye Su Thandar Khin Hnin May Ei Nilar Thiri Wai Phyu Moe Yamin Zin"), last: s("Aung Myint Oo Thein Kyaw Lwin Htun Maung Naing Win Zaw Soe Tun Min") },
  malayIndo: { male: s("Muhammad Ahmad Budi Agus Rizky Dimas Fajar Hafiz Arif Imran Siti Andi Bayu Wayan"), female: s("Siti Nur Dewi Sri Putri Ayu Rina Fitri Aisyah Nurul Intan Wulan Farah Kadek"), last: s("Santoso Wijaya Hidayat Saputra Pratama Kusuma Setiawan Abdullah Rahman Ismail Hassan Tan Lim Lee") },
  filipino: { male: s("Juan Jose Mark John Paul Michael Christian Jerome Angelo Ramon Rodel Jomar Carlo Ronaldo"), female: s("Maria Angel Princess Joy Kristine Mary Grace Jasmine Andrea Lovely Rowena Marites Charmaine Divina"), last: s("Santos Reyes Cruz Bautista Ocampo Garcia Mendoza Torres Villanueva Ramos Aquino Castillo Dela_Cruz Flores") },
  mongolian: { male: s("Bat-Erdene Ganbaatar Temuujin Batbayar Enkhbayar Bold Munkh-Erdene Tsogt Sukhbaatar Erdene Gantulga Altangerel Baatar Tömör"), female: s("Oyunchimeg Enkhjargal Sarangerel Altantsetseg Bolormaa Tsetseg Solongo Anu Nomin Undrakh Khulan Narantuya Saruul Delger"), last: s("Batbold Ganbold Enkhtuya Bayar Tsend Dorj Sukh Naran Purev Gombo Lkhagva Dash Jargal Ochir") },
  melanesian: { male: s("John Peter Joseph Michael Kila Simon Tom Waisale Josaia Ratu Paul Mathew Kerry Isaac"), female: s("Mary Grace Ruth Elizabeth Lucy Kiri Esther Margaret Mere Ana Salote Naomi Agnes Joyce"), last: s("Kila Wari Namaliu Somare Kaupa Tora Naidu Prasad Waqa Tuilagi Kuman Pato Raka Morea") },
  hebrew: { male: s("David Yosef Moshe Daniel Noam Itai Ariel Eitan Yonatan Avi Omer Uri Mohammed Ahmad"), female: s("Noa Maya Tamar Shira Yael Michal Rivka Sarah Talia Avigail Hila Leah Rania Lina"), last: s("Cohen Levi Mizrahi Peretz Biton Friedman Katz Shapiro Avraham Dahan Azoulay Ben-David Haddad Khoury") },
  westAfrica: { male: s("Chinedu Emeka Oluwaseun Tunde Kwame Kofi Yaw Ibrahim Musa Femi Babajide Uchenna Koffi Sena"), female: s("Ngozi Chiamaka Funmilayo Aisha Adwoa Ama Akosua Folake Blessing Esther Amina Ifeoma Afi Yetunde"), last: s("Okafor Adeyemi Okonkwo Mensah Boateng Bello Abubakar Eze Ogunleye Asante Owusu Nwosu Kouassi Agbeko") },
  sahel: { male: s("Moussa Amadou Ibrahima Ousmane Mamadou Abdoulaye Boubacar Issa Souleymane Adama Seydou Idrissa Cheikh Hamidou"), female: s("Aminata Fatoumata Mariam Aïssatou Kadiatou Awa Salimata Rokia Fanta Hawa Ramatou Khady Zeinabou Djeneba"), last: s("Diallo Traoré Coulibaly Keita Ouédraogo Sow Ndiaye Diop Konaté Sawadogo Camara Cissé Touré Mahamadou") },
  centralAfrica: { male: s("Jean-Pierre Patrice Joseph Christian Fiston Héritier Junior Didier Serge Blaise Arsène Glody Emmanuel Rodrigue"), female: s("Marie Grace Chantal Esther Ruth Benedicte Gloria Nadine Sandrine Clarisse Divine Merveille Josiane Pascaline"), last: s("Mbala Kabila Tshibanda Mukendi Ilunga Kasongo Ngoy Mabiala Nkounkou Mbarga Essomba Ndongo Fotso Ngando") },
  eastAfrica: { male: s("John Joseph Peter Emmanuel Daniel Juma Baraka Omondi Kipchoge Mwangi Tendai Bwalya Jean-Claude Deng"), female: s("Grace Mary Faith Joyce Mercy Neema Wanjiru Achieng Amani Zawadi Chisomo Uwase Nyakim Esther"), last: s("Mwangi Otieno Kamau Wanjiku Ochieng Mutua Kiprop Banda Phiri Mwale Nyirenda Habimana Uwimana Okello") },
  horn: { noFamily: true, male: s("Abebe Tesfaye Dawit Yohannes Getachew Mohamed Abdi Ahmed Hussein Tekle Bereket Solomon Mesfin Liban"), female: s("Tigist Hiwot Meron Selam Bethlehem Almaz Hana Hodan Fadumo Amina Ayaan Saba Rahel Mekdes"), last: s("Bekele Tadesse Haile Girma Alemu Mekonnen Abdullahi Warsame Farah Ali Gebre Desta Tesfay Omar") },
  southernAfrica: { male: s("Sipho Thabo Themba Bongani Lungile Mandla Tshepo Kagiso Tatenda Farai Johannes Pieter Kabelo Sibusiso"), female: s("Nomvula Thandiwe Lerato Palesa Zanele Nandi Busisiwe Naledi Rutendo Chipo Precious Anele Ayanda Refilwe"), last: s("Dlamini Nkosi Ndlovu Khumalo Mokoena Mahlangu Mthembu Moyo Ncube Sibanda van_der_Merwe Botha Molefe Shikongo") },
  malagasy: { male: s("Andry Hery Rivo Tiana Fidy Mamy Haja Naina Toky Lova Faly Solo Njaka Tsiry"), female: s("Voahangy Lalao Hanta Fara Noro Volana Mialy Tahina Soa Lanto Nirina Domoina Fanja Mbola"), last: s("Rakoto Rasoa Randriamampionona Rakotomalala Razafindrakoto Andrianarisoa Rabe Ravelo Rasolofo Randria Rajaonarison Ramanantsoa Rakotonirina Rabearivelo") },
}

export function displayName(pool: NamePool, first: string, last: string): string {
  const p = NAME_POOLS[pool]
  if (p.noFamily) return `${first} ${last}`
  return p.familyFirst ? `${last} ${first}` : `${first} ${last}`
}
